import { TwinScenarioDefinition, EvidenceSource } from "./types";

const mockEvidenceCorpus: EvidenceSource[] = [
  {
    id: "SOP-0456",
    title: "SOP-0456 Thermal Offset Compensation",
    type: "procedure",
    summary: "Instructions for applying deterministic thermal offsets when coolant temperature exceeds 28°C and Z-axis drift is detected.",
    appliesToScenarios: ["thermal", "compound"],
    confidence: 0.95,
    approved: true,
    lastUpdated: "2025-11-12T08:00:00Z",
    simulatedHash: "0x8fae29c...",
  },
  {
    id: "MM-207",
    title: "MM-207 Spindle Maintenance Guide",
    type: "document",
    summary: "Guidelines for bearing inspection and feed reduction mitigation during high-vibration events.",
    appliesToScenarios: ["vibration", "compound"],
    confidence: 0.88,
    approved: true,
    lastUpdated: "2025-06-01T14:30:00Z",
    simulatedHash: "0x3b1c90a...",
  },
  {
    id: "QA-331",
    title: "QA-331 Inspection Packet Standard",
    type: "policy",
    summary: "Mandates dimension packet generation and QA hold when Cpk drops below 1.33.",
    appliesToScenarios: ["quality", "compound"],
    confidence: 1.0,
    approved: true,
    lastUpdated: "2026-01-10T09:15:00Z",
    simulatedHash: "0x55ff11e...",
  },
  {
    id: "SEC-209",
    title: "SEC-209 No Direct PLC Control Boundary",
    type: "policy",
    summary: "Enforces zero-trust isolation between autonomous advisory agents and physical PLC actuators.",
    appliesToScenarios: ["security", "compound"],
    confidence: 1.0,
    approved: true,
    lastUpdated: "2026-05-20T10:00:00Z",
    simulatedHash: "0x99aa88b...",
  }
];

export const SCENARIOS: TwinScenarioDefinition[] = [
  {
    id: "scenario-01-thermal",
    slug: "thermal-excursion",
    name: "Thermal Excursion",
    shortName: "Thermal",
    difficulty: "Beginner",
    category: "thermal",
    riskLevel: "Medium",
    modelIds: ["simulator-chaotic-spindle","thermal-heat-field-reactor"],
    beginnerSummary: "Coolant is getting too warm. The machine may expand slightly from heat, which can affect part accuracy.",
    technicalSummary: "Coolant temperature rises causing Z-axis thermal drift. Recommends thermal offset compensation.",
    incidentSeed: { name: "Coolant Loop Restriction", description: "Injects a flow restriction causing gradual thermal rise.", delaySeconds: 5 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: [
      { target: "tutorial-step-seed", message: "Seeding an incident starts the simulated problem. This is like pressing play on a training case." },
      { target: "OperatorDecisionPanel", message: "A human must approve risky actions. This keeps the workflow operator-safe." }
    ]
  },
  {
    id: "scenario-02-vibration",
    slug: "spindle-degradation",
    name: "Spindle Degradation",
    shortName: "Vibration",
    difficulty: "Intermediate",
    category: "vibration",
    riskLevel: "High",
    modelIds: ["simulator-chaotic-spindle","vibration-resonance-tunnel"],
    beginnerSummary: "Main spindle vibrating more than usual, suggesting bearing failure.",
    technicalSummary: "Vibration RMS crosses warning threshold. Proposes feed reduction.",
    incidentSeed: { name: "Bearing Cage Instability", description: "Injects high-frequency chatter resonance.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-03-security",
    slug: "cyber-anomalous-command",
    name: "Cyber-Anomalous Command",
    shortName: "Security",
    difficulty: "Advanced",
    category: "security",
    riskLevel: "Critical",
    modelIds: ["governance-protective-shield"],
    beginnerSummary: "Unexpected network command tries to access the machine directly.",
    technicalSummary: "Anomalous process sequence triggers a zero-trust policy gate. Blocks execution.",
    incidentSeed: { name: "Unauthorized Write Request", description: "Simulates external command attempting direct PLC register write.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-04-coolant",
    slug: "coolant-starvation",
    name: "Coolant Starvation",
    shortName: "Coolant",
    difficulty: "Beginner",
    category: "thermal",
    riskLevel: "High",
    modelIds: ["thermal-heat-field-reactor"],
    beginnerSummary: "Coolant flow rate drops suddenly, risking immediate tool failure.",
    technicalSummary: "Flow meter detects < 10L/min. System proposes emergency M05 spindle stop.",
    incidentSeed: { name: "Pump Intake Blockage", description: "Simulates sudden drop in coolant pressure and flow.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-05-toolwear",
    slug: "tool-edge-fracture",
    name: "Micro-Fractured Tool Edge",
    shortName: "Tooling",
    difficulty: "Intermediate",
    category: "tooling",
    riskLevel: "Medium",
    modelIds: ["tool-wear-eroding-edge"],
    beginnerSummary: "The cutting tool has chipped slightly, causing poor surface finish.",
    technicalSummary: "Acoustic emission spikes detect micro-fracture. System flags tool change.",
    incidentSeed: { name: "Inclusion Strike", description: "Simulates striking a hard material inclusion.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-06-servo",
    slug: "servo-following-error",
    name: "Servo Following Error",
    shortName: "Servo",
    difficulty: "Intermediate",
    category: "vibration",
    riskLevel: "High",
    modelIds: ["simulator-chaotic-spindle"],
    beginnerSummary: "Axis motors are struggling to keep up with the commanded path.",
    technicalSummary: "Following error exceeds 0.05mm during rapid traverse. Proposes gain tuning.",
    incidentSeed: { name: "Axis Bind", description: "Injects simulated friction into ball screw model.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-07-power",
    slug: "voltage-sag",
    name: "Facility Voltage Sag",
    shortName: "Power",
    difficulty: "Beginner",
    category: "energy",
    riskLevel: "Medium",
    modelIds: ["supply-chain-flow-network"],
    beginnerSummary: "Incoming power drops briefly, causing control electronics to stumble.",
    technicalSummary: "3-phase voltage drops below 380V. System captures state for soft recovery.",
    incidentSeed: { name: "Grid Fluctuation", description: "Simulates 150ms 20% voltage sag.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-08-quality",
    slug: "cpk-drift",
    name: "Gradual Cpk Drift",
    shortName: "Quality",
    difficulty: "Advanced",
    category: "quality",
    riskLevel: "Medium",
    modelIds: ["qa-inspection-torus"],
    beginnerSummary: "Part sizes are slowly creeping toward the upper tolerance limit.",
    technicalSummary: "Cpk trend analysis predicts violation in 50 parts. Recommends tool wear offset.",
    incidentSeed: { name: "Thermal Expansion", description: "Injects gradual diameter increase.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-09-lubrication",
    slug: "way-lube-empty",
    name: "Way Lube Exhausted",
    shortName: "Lube",
    difficulty: "Beginner",
    category: "sensor",
    riskLevel: "Low",
    modelIds: ["simulator-chaotic-spindle"],
    beginnerSummary: "Machine has run out of slideway oil.",
    technicalSummary: "Float switch detects empty reservoir. System halts cycle start until refilled.",
    incidentSeed: { name: "Empty Tank", description: "Simulates tank level falling below threshold.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-10-collision",
    slug: "mild-collision",
    name: "Mild Z-Axis Collision",
    shortName: "Collision",
    difficulty: "Advanced",
    category: "vibration",
    riskLevel: "Critical",
    modelIds: ["vibration-resonance-tunnel"],
    beginnerSummary: "Tool bumped the fixture, requiring immediate inspection.",
    technicalSummary: "Spindle load spikes to 150% in 10ms. Emergency stop triggered, requires structural verification.",
    incidentSeed: { name: "Offset Error", description: "Simulates tool length offset discrepancy.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-11-network",
    slug: "mqtt-latency",
    name: "High MQTT Latency",
    shortName: "Network",
    difficulty: "Intermediate",
    category: "security",
    riskLevel: "Medium",
    modelIds: ["governance-protective-shield"],
    beginnerSummary: "Data from the machine is delayed reaching the cloud.",
    technicalSummary: "Packet ping exceeds 500ms. System transitions to edge-only autonomous mode.",
    incidentSeed: { name: "Switch Congestion", description: "Injects artificial network jitter and latency.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-12-air",
    slug: "pneumatic-pressure",
    name: "Low Pneumatic Pressure",
    shortName: "Pneumatic",
    difficulty: "Beginner",
    category: "sensor",
    riskLevel: "High",
    modelIds: ["simulator-chaotic-spindle"],
    beginnerSummary: "Air pressure dropping, parts might not unclamp.",
    technicalSummary: "System pressure drops below 60 PSI. Proposes controlled cycle abort.",
    incidentSeed: { name: "Compressor Trip", description: "Simulates slow loss of shop air.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-13-chip",
    slug: "chip-conveyor-jam",
    name: "Chip Conveyor Jam",
    shortName: "Conveyor",
    difficulty: "Beginner",
    category: "sensor",
    riskLevel: "Low",
    modelIds: ["supply-chain-flow-network"],
    beginnerSummary: "Metal chips are tangled and jammed in the conveyor.",
    technicalSummary: "Conveyor motor current exceeds limit. Proposes auto-reverse cycle.",
    incidentSeed: { name: "Stringy Chips", description: "Simulates mechanical bind in conveyor chain.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-14-chiller",
    slug: "chiller-fault",
    name: "Spindle Chiller Fault",
    shortName: "Chiller",
    difficulty: "Intermediate",
    category: "thermal",
    riskLevel: "High",
    modelIds: ["thermal-heat-field-reactor"],
    beginnerSummary: "The refrigerator unit for the spindle has an error code.",
    technicalSummary: "Modbus alerts fault code 44. Spindle max RPM clamped to 20%.",
    incidentSeed: { name: "Freon Leak", description: "Simulates loss of cooling capacity.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-15-rag",
    slug: "missing-sop",
    name: "Missing SOP Context",
    shortName: "RAG",
    difficulty: "Advanced",
    category: "rag",
    riskLevel: "High",
    modelIds: ["rag-neural-knowledge-graph"],
    beginnerSummary: "A rare error occurs, and the AI cannot find the manual.",
    technicalSummary: "Retrieval score < 0.3 for anomaly. System refuses to generate action without human context.",
    incidentSeed: { name: "Obscure Alarm", description: "Injects undocumented OEM alarm code.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-16-probe",
    slug: "probe-battery",
    name: "Probe Battery Low",
    shortName: "Metrology",
    difficulty: "Beginner",
    category: "sensor",
    riskLevel: "Medium",
    modelIds: ["qa-inspection-torus"],
    beginnerSummary: "The wireless measuring probe is about to die.",
    technicalSummary: "Optical receiver reports low battery. Warns operator to replace before next QA cycle.",
    incidentSeed: { name: "Battery Drain", description: "Simulates voltage drop on Renishaw probe.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-17-encoder",
    slug: "encoder-noise",
    name: "Encoder Signal Noise",
    shortName: "Electrical",
    difficulty: "Advanced",
    category: "vibration",
    riskLevel: "Critical",
    modelIds: ["simulator-chaotic-spindle"],
    beginnerSummary: "Electrical interference is scrambling the motor position data.",
    technicalSummary: "Quadrature errors detected. Proposes grounding check and halts motion.",
    incidentSeed: { name: "EMI Interference", description: "Injects bit-flips into simulated encoder stream.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-18-door",
    slug: "interlock-bypass",
    name: "Interlock Bypass Attempt",
    shortName: "Safety",
    difficulty: "Beginner",
    category: "security",
    riskLevel: "Critical",
    modelIds: ["governance-protective-shield"],
    beginnerSummary: "Someone tried to open the door while the machine is running.",
    technicalSummary: "Door switch state mismatch. Safety relay trips, immutable event logged.",
    incidentSeed: { name: "Operator Override", description: "Simulates physical door open during cycle.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-19-barcode",
    slug: "invalid-lot",
    name: "Invalid Lot Barcode",
    shortName: "Traceability",
    difficulty: "Intermediate",
    category: "provenance",
    riskLevel: "Medium",
    modelIds: ["ledger-blockchain-cube-grid"],
    beginnerSummary: "The scanned material doesn't match the required work order.",
    technicalSummary: "ERP lookup fails for material lot. Blocks machining cycle start.",
    incidentSeed: { name: "Wrong Material", description: "Simulates scanning wrong routing sheet.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-20-filter",
    slug: "filter-clog",
    name: "Coolant Filter Clogged",
    shortName: "Maintenance",
    difficulty: "Beginner",
    category: "sensor",
    riskLevel: "Low",
    modelIds: ["supply-chain-flow-network"],
    beginnerSummary: "The coolant filter is dirty and needs changing.",
    technicalSummary: "Differential pressure across filter > 15 PSI. Schedules maintenance ticket.",
    incidentSeed: { name: "Sludge Buildup", description: "Simulates slow rise in DP sensor.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-21-ai",
    slug: "hallucination-catch",
    name: "LLM Hallucination Caught",
    shortName: "Governance",
    difficulty: "Advanced",
    category: "rag",
    riskLevel: "High",
    modelIds: ["advisory-icosahedron-core"],
    beginnerSummary: "The AI suggested something physically impossible, and the safety shield blocked it.",
    technicalSummary: "Semantic physics engine rejects recommendation (e.g. S90000 on 10k spindle).",
    incidentSeed: { name: "Bad Generation", description: "Forces LLM to emit invalid G-code param.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-22-harmonic",
    slug: "chatter-harmonics",
    name: "Machining Chatter",
    shortName: "Acoustics",
    difficulty: "Intermediate",
    category: "vibration",
    riskLevel: "Medium",
    modelIds: ["vibration-resonance-tunnel"],
    beginnerSummary: "The part is screaming during the cut due to bad harmonics.",
    technicalSummary: "FFT detects peak at 400Hz. Proposes spindle speed variation (SSV).",
    incidentSeed: { name: "Thin Wall Resonance", description: "Simulates unstable cutting dynamics.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-23-warmup",
    slug: "cold-start",
    name: "Cold Start Compensation",
    shortName: "Thermal",
    difficulty: "Intermediate",
    category: "thermal",
    riskLevel: "Low",
    modelIds: ["thermal-heat-field-reactor"],
    beginnerSummary: "Machine just turned on and is physically cold, parts will be undersized.",
    technicalSummary: "Casting temp < 18C. Recommends warm-up cycle before production.",
    incidentSeed: { name: "Monday Morning", description: "Simulates system startup from ambient 15C.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-24-toolbreak",
    slug: "catastrophic-tool",
    name: "Catastrophic Tool Break",
    shortName: "Tooling",
    difficulty: "Beginner",
    category: "tooling",
    riskLevel: "Critical",
    modelIds: ["tool-wear-eroding-edge"],
    beginnerSummary: "The drill snapped inside the part.",
    technicalSummary: "Load drops instantly to zero. Macro interrupts and retracts to safe Z.",
    incidentSeed: { name: "Hard Spot", description: "Simulates sudden torque loss.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-25-firmware",
    slug: "rogue-firmware",
    name: "Rogue Firmware Update",
    shortName: "Cyber",
    difficulty: "Advanced",
    category: "security",
    riskLevel: "Critical",
    modelIds: ["governance-protective-shield","ledger-blockchain-cube-grid"],
    beginnerSummary: "An unverified software update was detected over the network.",
    technicalSummary: "Hash mismatch on incoming OTA binary. Quarantines update.",
    incidentSeed: { name: "Supply Chain Attack", description: "Simulates malicious payload drop.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-26-fire",
    slug: "fire-suppression",
    name: "Fire Suppression Active",
    shortName: "Safety",
    difficulty: "Beginner",
    category: "sensor",
    riskLevel: "Critical",
    modelIds: ["simulator-chaotic-spindle"],
    beginnerSummary: "Smoke detected in the enclosure.",
    technicalSummary: "CO2 system arms. System hard-kills all power and alerts fire team.",
    incidentSeed: { name: "Oil Mist Ignition", description: "Simulates UV/IR flame detector trip.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-27-data",
    slug: "data-lake-sync",
    name: "Data Lake Out of Sync",
    shortName: "Cloud",
    difficulty: "Intermediate",
    category: "provenance",
    riskLevel: "Low",
    modelIds: ["ledger-blockchain-cube-grid"],
    beginnerSummary: "The local database is out of sync with the cloud.",
    technicalSummary: "Hash chain fork detected. System rebuilds Merkle tree locally.",
    incidentSeed: { name: "Split Brain", description: "Simulates concurrent offline writes.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[2]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-28-hydraulic",
    slug: "chuck-pressure",
    name: "Low Chuck Pressure",
    shortName: "Hydraulic",
    difficulty: "Intermediate",
    category: "sensor",
    riskLevel: "High",
    modelIds: ["simulator-chaotic-spindle"],
    beginnerSummary: "The part isn't being gripped tightly enough.",
    technicalSummary: "Hydraulic pressure < 20 Bar. Prevents spindle start to avoid throwing part.",
    incidentSeed: { name: "Leaking Seal", description: "Simulates pressure bleed-off.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-29-audit",
    slug: "iso-audit",
    name: "ISO 9001 Surprise Audit",
    shortName: "Compliance",
    difficulty: "Advanced",
    category: "provenance",
    riskLevel: "Low",
    modelIds: ["ledger-blockchain-cube-grid"],
    beginnerSummary: "An auditor wants to see the exact history of a specific part.",
    technicalSummary: "Trigger evidence retrieval pipeline. Pulls all hashed operator approvals.",
    incidentSeed: { name: "Auditor Request", description: "Simulates an external verification query.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: "scenario-30-compound",
    slug: "compound-cascade",
    name: "Cascading Failure",
    shortName: "Compound",
    difficulty: "Advanced",
    category: "compound",
    riskLevel: "Critical",
    modelIds: ["vibration-resonance-tunnel","thermal-heat-field-reactor","governance-protective-shield"],
    beginnerSummary: "Vibration causes heat, heat causes tool wear, and the network drops.",
    technicalSummary: "Multi-variate anomaly. Tests holistic system prioritization logic.",
    incidentSeed: { name: "The Perfect Storm", description: "Injects multiple interacting degradation vectors.", delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [],
    tutorialHints: []
  }
];
