import { TwinScenarioDefinition, EvidenceSource } from "./types";

const mockEvidenceCorpus: EvidenceSource[] = [
  {
    id: "SOP-0456",
    title: "SOP-0456 Thermal Offset Compensation",
    type: "procedure",
    summary: "Instructions for applying deterministic thermal offsets when coolant temperature exceeds 28°C and Z-axis drift is detected.",
    appliesToScenarios: ["thermal", "compound"],
    confidence: 0.95,
    approved: true,
    lastUpdated: "2025-11-12T08:00:00Z",
    simulatedHash: "0x8fae29c...",
  },
  {
    id: "MM-207",
    title: "MM-207 Spindle Maintenance Guide",
    type: "document",
    summary: "Guidelines for bearing inspection and feed reduction mitigation during high-vibration events.",
    appliesToScenarios: ["vibration", "compound"],
    confidence: 0.88,
    approved: true,
    lastUpdated: "2025-06-01T14:30:00Z",
    simulatedHash: "0x3b1c90a...",
  },
  {
    id: "QA-331",
    title: "QA-331 Inspection Packet Standard",
    type: "policy",
    summary: "Mandates dimension packet generation and QA hold when Cpk drops below 1.33.",
    appliesToScenarios: ["quality", "compound"],
    confidence: 1.0,
    approved: true,
    lastUpdated: "2026-01-10T09:15:00Z",
    simulatedHash: "0x55ff11e...",
  },
  {
    id: "SEC-209",
    title: "SEC-209 No Direct PLC Control Boundary",
    type: "policy",
    summary: "Enforces zero-trust isolation between autonomous advisory agents and physical PLC actuators.",
    appliesToScenarios: ["security", "compound"],
    confidence: 1.0,
    approved: true,
    lastUpdated: "2026-05-20T10:00:00Z",
    simulatedHash: "0x99aa88b...",
  }
];

export const SCENARIOS: TwinScenarioDefinition[] = [
  {
    id: "scenario-01-thermal",
    slug: "thermal-excursion",
    name: "Thermal Excursion",
    shortName: "Thermal",
    difficulty: "Beginner",
    category: "thermal",
    riskLevel: "Medium",
    modelIds: ["simulator-chaotic-spindle", "thermal-heat-field-reactor"],
    beginnerSummary: "Coolant is getting too warm. The machine may expand slightly from heat, which can affect part accuracy. The simulator will show how the system detects this and asks a human before taking any action.",
    technicalSummary: "Coolant temperature rises from 20.6 °C to 31.8 °C over the simulated run, causing Z-axis thermal drift and a modeled Cpk degradation risk. The advisory engine recommends thermal offset compensation with operator approval and shadow-mode validation.",
    incidentSeed: { name: "Coolant Loop Restriction", description: "Injects a flow restriction causing gradual thermal rise.", delaySeconds: 5 },
    signals: [
      {
        id: "sig-temp", name: "Coolant Temperature", unit: "°C", baseline: 20.6, watchThreshold: 25.0, warningThreshold: 28.0, criticalThreshold: 32.0, noiseAmplitude: 0.2, rampRate: 30, incidentMagnitude: 11.2
      },
      {
        id: "sig-cpk", name: "Process Cpk", unit: "index", baseline: 1.66, watchThreshold: 1.33, warningThreshold: 1.0, criticalThreshold: 0.8, noiseAmplitude: 0.05, rampRate: 40, incidentMagnitude: -0.6
      }
    ],
    evidencePlan: [mockEvidenceCorpus[0], mockEvidenceCorpus[2]],
    recommendations: [
      { id: "rec-1", text: "Apply Thermal Offset Compensation", rationale: "SOP-0456 supports thermal offset review when Z-axis drift exceeds +1.5 µm and coolant temperature rises above the watch threshold.", confidence: 0.92, requiresApproval: true, shadowActionAvailable: true }
    ],
    tutorialHints: [
      { target: "IncidentSeeder", message: "Seeding an incident starts the simulated problem. This is like pressing play on a training case." },
      { target: "OperatorDecisionPanel", message: "A human must approve risky actions. This keeps the workflow operator-safe." }
    ]
  },
  {
    id: "scenario-02-vibration",
    slug: "spindle-degradation",
    name: "Spindle Degradation",
    shortName: "Vibration",
    difficulty: "Intermediate",
    category: "vibration",
    riskLevel: "High",
    modelIds: ["simulator-chaotic-spindle", "vibration-resonance-tunnel"],
    beginnerSummary: "The main spindle is vibrating more than usual, suggesting a bearing might be failing. We need to reduce speed to save the part and schedule maintenance.",
    technicalSummary: "Vibration RMS crosses the 4.5 mm/s warning threshold, indicating potential bearing instability. The system proposes a process parameter adjustment (feed reduction) in shadow mode, requiring explicit operator approval.",
    incidentSeed: { name: "Bearing Cage Instability", description: "Injects a high-frequency chatter resonance.", delaySeconds: 8 },
    signals: [
      {
        id: "sig-vib", name: "Vibration RMS", unit: "mm/s", baseline: 1.2, watchThreshold: 2.8, warningThreshold: 4.5, criticalThreshold: 7.1, noiseAmplitude: 0.4, rampRate: 15, incidentMagnitude: 5.5
      }
    ],
    evidencePlan: [mockEvidenceCorpus[1]],
    recommendations: [
      { id: "rec-2", text: "Reduce Feed Rate & Schedule Inspection", rationale: "MM-207 advises feed reduction to mitigate bearing chatter until a physical inspection can be completed.", confidence: 0.85, requiresApproval: true, shadowActionAvailable: true }
    ]
  },
  {
    id: "scenario-07-security",
    slug: "cyber-anomalous-command",
    name: "Cyber-Anomalous Command Pattern",
    shortName: "Security",
    difficulty: "Advanced",
    category: "security",
    riskLevel: "Critical",
    modelIds: ["governance-protective-shield", "ledger-blockchain-cube-grid"],
    beginnerSummary: "An unexpected network command tries to access the machine directly. The Governance Shield blocks it because no AI or network agent is allowed to directly control physical hardware without human approval.",
    technicalSummary: "An anomalous process sequence triggers a zero-trust policy gate (SEC-209). The orchestrator blocks the execution path, quarantines the session, and generates an immutable ledger hash for forensic replay.",
    incidentSeed: { name: "Unauthorized Write Request", description: "Simulates an external command attempting a direct PLC register write.", delaySeconds: 3 },
    signals: [
      {
        id: "sig-sec", name: "Anomaly Score", unit: "index", baseline: 0.05, watchThreshold: 0.5, warningThreshold: 0.8, criticalThreshold: 0.95, noiseAmplitude: 0.02, rampRate: 2, incidentMagnitude: 0.92
      }
    ],
    evidencePlan: [mockEvidenceCorpus[3]],
    recommendations: [
      { id: "rec-3", text: "Quarantine Session & Block Execution", rationale: "SEC-209 strictly prohibits direct PLC actuation without cryptographically signed operator shadowing.", confidence: 0.99, requiresApproval: false, shadowActionAvailable: false }
    ]
  }
,
  {
    id: 'scenario-04-mock',
    slug: 'mock-incident-04',
    name: 'Tutorial Scenario 04',
    shortName: 'Tutorial 04',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 04', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-05-mock',
    slug: 'mock-incident-05',
    name: 'Tutorial Scenario 05',
    shortName: 'Tutorial 05',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 05', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-06-mock',
    slug: 'mock-incident-06',
    name: 'Tutorial Scenario 06',
    shortName: 'Tutorial 06',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 06', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-07-mock',
    slug: 'mock-incident-07',
    name: 'Tutorial Scenario 07',
    shortName: 'Tutorial 07',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 07', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-08-mock',
    slug: 'mock-incident-08',
    name: 'Tutorial Scenario 08',
    shortName: 'Tutorial 08',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 08', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-09-mock',
    slug: 'mock-incident-09',
    name: 'Tutorial Scenario 09',
    shortName: 'Tutorial 09',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 09', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-10-mock',
    slug: 'mock-incident-10',
    name: 'Tutorial Scenario 10',
    shortName: 'Tutorial 10',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 10', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-11-mock',
    slug: 'mock-incident-11',
    name: 'Tutorial Scenario 11',
    shortName: 'Tutorial 11',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 11', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-12-mock',
    slug: 'mock-incident-12',
    name: 'Tutorial Scenario 12',
    shortName: 'Tutorial 12',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 12', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-13-mock',
    slug: 'mock-incident-13',
    name: 'Tutorial Scenario 13',
    shortName: 'Tutorial 13',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 13', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-14-mock',
    slug: 'mock-incident-14',
    name: 'Tutorial Scenario 14',
    shortName: 'Tutorial 14',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 14', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-15-mock',
    slug: 'mock-incident-15',
    name: 'Tutorial Scenario 15',
    shortName: 'Tutorial 15',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 15', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-16-mock',
    slug: 'mock-incident-16',
    name: 'Tutorial Scenario 16',
    shortName: 'Tutorial 16',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 16', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-17-mock',
    slug: 'mock-incident-17',
    name: 'Tutorial Scenario 17',
    shortName: 'Tutorial 17',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 17', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-18-mock',
    slug: 'mock-incident-18',
    name: 'Tutorial Scenario 18',
    shortName: 'Tutorial 18',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 18', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-19-mock',
    slug: 'mock-incident-19',
    name: 'Tutorial Scenario 19',
    shortName: 'Tutorial 19',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 19', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-20-mock',
    slug: 'mock-incident-20',
    name: 'Tutorial Scenario 20',
    shortName: 'Tutorial 20',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 20', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-21-mock',
    slug: 'mock-incident-21',
    name: 'Tutorial Scenario 21',
    shortName: 'Tutorial 21',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 21', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-22-mock',
    slug: 'mock-incident-22',
    name: 'Tutorial Scenario 22',
    shortName: 'Tutorial 22',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 22', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-23-mock',
    slug: 'mock-incident-23',
    name: 'Tutorial Scenario 23',
    shortName: 'Tutorial 23',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 23', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-24-mock',
    slug: 'mock-incident-24',
    name: 'Tutorial Scenario 24',
    shortName: 'Tutorial 24',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 24', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-25-mock',
    slug: 'mock-incident-25',
    name: 'Tutorial Scenario 25',
    shortName: 'Tutorial 25',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 25', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-26-mock',
    slug: 'mock-incident-26',
    name: 'Tutorial Scenario 26',
    shortName: 'Tutorial 26',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 26', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-27-mock',
    slug: 'mock-incident-27',
    name: 'Tutorial Scenario 27',
    shortName: 'Tutorial 27',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 27', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-28-mock',
    slug: 'mock-incident-28',
    name: 'Tutorial Scenario 28',
    shortName: 'Tutorial 28',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 28', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-29-mock',
    slug: 'mock-incident-29',
    name: 'Tutorial Scenario 29',
    shortName: 'Tutorial 29',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 29', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  },
  {
    id: 'scenario-30-mock',
    slug: 'mock-incident-30',
    name: 'Tutorial Scenario 30',
    shortName: 'Tutorial 30',
    difficulty: 'Beginner',
    category: 'quality',
    riskLevel: 'Low',
    modelIds: ['simulator-chaotic-spindle'],
    beginnerSummary: 'A basic tutorial scenario generated for training.',
    technicalSummary: 'Simulated tutorial condition for operator training.',
    incidentSeed: { name: 'Tutorial Seed 30', description: 'Auto-generated tutorial seed', delaySeconds: 3 },
    signals: [],
    evidencePlan: [mockEvidenceCorpus[0]],
    recommendations: [],
    tutorialHints: []
  }
];